/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type DaemonJsonrpcType = Request | Request[];
export type Request = GetTracks | GetLocalStorage;

export interface GetTracks {
  jsonrpc: "2.0";
  id: string;
  method: "getTracks";
  params: {
    since: number;
    platform: string;
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
export interface GetLocalStorage {
  jsonrpc: "2.0";
  id: string;
  method: "getLocalStorage";
  params: {
    platform: string;
    [k: string]: unknown;
  };
  [k: string]: unknown;
}

